export const state = () => ({
  users: [
    {
      id: 1,
      name: 'Peter Nobels',
      username: 'peter_nobels',
      about: 'lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod. ',
      nfts: [{
        id: 1,
        name: 'How to DAO it',
        imageUrl: "https://img.freepik.com/premium-photo/astronaut-outer-open-space-planet-earth-stars-provide-background-erforming-space-planet-earth-sunrise-sunset-our-home-iss-elements-this-image-furnished-by-nasa_150455-16829.jpg?w=900",
        fee: 10,
        event: 'How to DAO it',
        eventId: 1,
        ownerAddress: '0x1234567890',
        creationDate: '20-06-2022',
      }, {
        id: 2,
        name: 'How to DAO it 2',
        imageUrl: "https://cdn.mos.cms.futurecdn.net/qTmvroik2NtHVGsfCHyyxF-1200-80.jpg.webp",
        fee: 20,
        event: 'How to DAO it 2',
        eventId: 2,
        ownerAddress: '0x1234567890',
        creationDate: '24-11-2022',
      }, {
        id: 3,
        name: 'How to DAO it 3',
        imageUrl: "https://cdn.mos.cms.futurecdn.net/mPFET8wxkZENQazxvRg7K5-1200-80.jpg.webp",
        fee: 30,
        event: 'How to DAO it 3',
        eventId: 3,
        ownerAddress: '0x1234567890',
        creationDate: '12-02-2023',
      }, {
        id: 4,
        name: 'How to DAO it 4',
        imageUrl: "https://lisk.com/sites/default/files/images/2020-06/official-lisk-release-MAIN%402x.png",
        fee: 30,
        event: 'How to DAO it 4',
        eventId: 4,
        ownerAddress: '0x1234567890',
        creationDate: '12-02-2023',
      }, {
        id: 5,
        name: 'How to DAO it 5',
        imageUrl: "https://thumbs.dreamstime.com/z/gold-medal-isolated-white-d-illustration-medal-123991138.jpg",
        fee: 30,
        event: 'How to DAO it 5',
        eventId: 5,
        ownerAddress: '0x1234567890',
        creationDate: '12-02-2023',
      }]
    },
    {
      id: 2,
      name: 'Matthias',
      username: 'matthias',
      about: 'I am a web developer from the Netherlands. I love to code and I love to share my knowledge with others. ',
      nfts: [{
        id: 1,
        name: 'How to DAO it',
        imageUrl: "",
        fee: 10,
        ownerAddress: '0x1234567890',
        creationDate: new Date('20-06-2022'),
      }, {
        id: 2,
        name: 'How to DAO it 2',
        imageUrl: "x124",
        fee: 20,
        ownerAddress: '0x1234567890',
        creationDate: new Date('24-11-2022'),
      }, {
        id: 3,
        name: 'How to DAO it 3',
        imageUrl: "x125",
        fee: 30,
        ownerAddress: '0x1234567890',
        creationDate: new Date('12-02-2023'),
      }]
    },
  ],

})
